/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apartment_management;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Khoza
 */
public class Settings_Page extends javax.swing.JFrame {
    
    public Visitors_Capturing_Page VisitorsCapturing;
    public Dashboard_Page Dashboard;

    /**
     * Creates new form Settings_Page
     */
    public Settings_Page() {
        initComponents();
        
        VisitorsCapturing = new Visitors_Capturing_Page();
        //Dashboard = new Dashboard_Page();
        
         //fileMenu();
         //JMenuBarEvents();
        seticonImage();
    }
    
    /*javax.swing.JMenuBar mbMenuBar = new javax.swing.JMenuBar();
    javax.swing.JMenu mMenu = new javax.swing.JMenu("File");
    
    javax.swing.JMenuItem mMenuVisitorCapturing = new javax.swing.JMenuItem("Visitor's Capturing");
    javax.swing.JMenuItem mMenuDashboard = new javax.swing.JMenuItem("Dashboard");
    javax.swing.JMenuItem mMenuAbout = new javax.swing.JMenuItem("About");

    javax.swing.JMenuItem mMenuExit = new javax.swing.JMenuItem("Exit Application");
    
    private void fileMenu(){
        
        mMenu.add(mMenuVisitorCapturing);
        mMenu.add(mMenuDashboard);
        
        mMenu.add(mMenuAbout);
        
        mMenu.add(mMenuExit);
        mbMenuBar.add(mMenu);
        
        this.setJMenuBar(mbMenuBar);
    }
    
    private void JMenuBarEvents() {
        mMenuVisitorCapturing.addActionListener( new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
            VisitorsCapturing.setVisible(true);
            VisitorsCapturing.toFront();          
            }
        });
        
        mMenuDashboard.addActionListener( new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
            Dashboard.setVisible(true);
            Dashboard.toFront();
            }
        });
        
        mMenuExit.addActionListener( new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
            
        int response = JOptionPane.showConfirmDialog(null,"Do you want to Exit Application? " , "CONFIRM", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        else if(response== JOptionPane.NO_OPTION){
            setVisible(true);
        }
            }
        });
        
        mMenuAbout.addActionListener( new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                JOptionPane.showMessageDialog(null,"Apartment \n"
                        + "Add Info \n"
                        + "Add Info \n"
                        + "Add Info \n"
                        + "Add Info\n \n"
                        + "Add Info \n"
                        + "Est.2020", " ABOUT REYAVAYA", JOptionPane.PLAIN_MESSAGE);
            }
        });
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnChangeName = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNewName = new javax.swing.JTextField();
        txtCornfirmNewName = new javax.swing.JTextField();
        txtCurrentPassword = new javax.swing.JTextField();
        txtNewPassword = new javax.swing.JTextField();
        txtCornfirmNewPassword = new javax.swing.JTextField();
        SettingsBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SETTINGS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jPanel1.setLayout(null);
        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(400, 40, 10, 350);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jPanel1.add(jTable1);
        jTable1.setBounds(0, 0, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartment_management/Background/icons8-user-48 (3).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 70, 48, 50);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(80, 60, 280, 10);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(450, 60, 280, 10);

        btnChangeName.setBackground(new java.awt.Color(0, 0, 0));
        btnChangeName.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnChangeName.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeName.setText("Change");
        btnChangeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeNameActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangeName);
        btnChangeName.setBounds(80, 280, 100, 30);

        btnChangePassword.setBackground(new java.awt.Color(0, 0, 0));
        btnChangePassword.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setText("Change");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangePassword);
        btnChangePassword.setBounds(450, 280, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartment_management/Background/icons8-user-48 (1).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 70, 60, 50);

        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        jPanel1.add(txtName);
        txtName.setBounds(80, 140, 280, 30);

        txtNewName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewNameFocusLost(evt);
            }
        });
        jPanel1.add(txtNewName);
        txtNewName.setBounds(80, 190, 280, 30);

        txtCornfirmNewName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCornfirmNewNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCornfirmNewNameFocusLost(evt);
            }
        });
        jPanel1.add(txtCornfirmNewName);
        txtCornfirmNewName.setBounds(80, 240, 280, 30);

        txtCurrentPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCurrentPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCurrentPasswordFocusLost(evt);
            }
        });
        jPanel1.add(txtCurrentPassword);
        txtCurrentPassword.setBounds(450, 140, 280, 30);

        txtNewPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewPasswordFocusLost(evt);
            }
        });
        jPanel1.add(txtNewPassword);
        txtNewPassword.setBounds(450, 190, 280, 30);

        txtCornfirmNewPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCornfirmNewPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCornfirmNewPasswordFocusLost(evt);
            }
        });
        jPanel1.add(txtCornfirmNewPassword);
        txtCornfirmNewPassword.setBounds(450, 240, 280, 30);

        SettingsBack.setBackground(new java.awt.Color(0, 0, 0));
        SettingsBack.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        SettingsBack.setForeground(new java.awt.Color(255, 255, 255));
        SettingsBack.setText("Back");
        SettingsBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsBackActionPerformed(evt);
            }
        });
        jPanel1.add(SettingsBack);
        SettingsBack.setBounds(560, 280, 100, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current Password ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 120, 120, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 174, 90, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cornfirm New Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(450, 220, 150, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Current User  Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 120, 110, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("New User Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 170, 80, 30);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm New User Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 220, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartment_management/Background/pexels-artem-lysenko-3825673 (Background).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNewNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewNameFocusGained
        
    }//GEN-LAST:event_txtNewNameFocusGained

    private void txtNewNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewNameFocusLost
        
    }//GEN-LAST:event_txtNewNameFocusLost

    private void txtCornfirmNewNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCornfirmNewNameFocusGained
        
    }//GEN-LAST:event_txtCornfirmNewNameFocusGained

    private void txtCornfirmNewNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCornfirmNewNameFocusLost
        
    }//GEN-LAST:event_txtCornfirmNewNameFocusLost

    private void txtCurrentPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCurrentPasswordFocusGained
        
    }//GEN-LAST:event_txtCurrentPasswordFocusGained

    private void txtCurrentPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCurrentPasswordFocusLost
        
    }//GEN-LAST:event_txtCurrentPasswordFocusLost

    private void txtNewPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPasswordFocusGained
        
    }//GEN-LAST:event_txtNewPasswordFocusGained

    private void txtNewPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPasswordFocusLost
        
    }//GEN-LAST:event_txtNewPasswordFocusLost

    private void txtCornfirmNewPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCornfirmNewPasswordFocusGained
        
    }//GEN-LAST:event_txtCornfirmNewPasswordFocusGained

    private void txtCornfirmNewPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCornfirmNewPasswordFocusLost
        
    }//GEN-LAST:event_txtCornfirmNewPasswordFocusLost

    private void SettingsBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsBackActionPerformed
        this.toBack();
        Dashboard.setVisible(true);
        Dashboard.toFront();
        this.hide();
    }//GEN-LAST:event_SettingsBackActionPerformed

    private void btnChangeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeNameActionPerformed
        if (txtName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"User Name Required");
            txtName.requestFocusInWindow();
        }
        else if (txtNewName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"New User Required");
            txtNewName.requestFocusInWindow();
        }
        else if (txtCornfirmNewName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Cornfirm New User Name");
            txtCornfirmNewName.requestFocusInWindow();
        }
        else 
        {
            //Add code to change user info
        }
            
    }//GEN-LAST:event_btnChangeNameActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        if (txtCurrentPassword.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Password Required");
            txtCurrentPassword.requestFocusInWindow();
        }
        else if (txtNewPassword.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Password Required");
            txtNewPassword.requestFocusInWindow();
        }
        else if (txtCornfirmNewPassword.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Password Required");
            txtCornfirmNewPassword.requestFocusInWindow();
        }
        else 
        {
            //Add code to change user info
        }
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SettingsBack;
    private javax.swing.JButton btnChangeName;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCornfirmNewName;
    private javax.swing.JTextField txtCornfirmNewPassword;
    private javax.swing.JTextField txtCurrentPassword;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNewName;
    private javax.swing.JTextField txtNewPassword;
    // End of variables declaration//GEN-END:variables

   private void seticonImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8-building-50.png"))); 
    }
}
