/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apartment_management;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.BorderLayout;
import javax.swing.*;
import java.util.Vector;
import java.awt.Color;

/**
 *
 * @author Daniel Khoza
 */
public class Visitors_Capturing_Page extends javax.swing.JFrame {
    //public Settings_Page SettingsPage;
    public Dashboard_Page Dashboard;

    /**
     * Creates new form Capturing_Page
     */
    public Visitors_Capturing_Page() {
        initComponents();
        //SettingsPage = new Settings_Page();
        //Dashboard = new Dashboard_Page();
        //JMenuBarEvents();
        //fileMenu();
        //mGetValues();
        seticonImage();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCapture = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtVisitorName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtApartmentCode = new javax.swing.JTextField();
        CapturingBack = new javax.swing.JButton();
        btnRecords = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VISITORS CAPTURING");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(908, 508));
        setResizable(false);

        jPanel1.setLayout(null);

        btnCapture.setBackground(new java.awt.Color(0, 0, 0));
        btnCapture.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnCapture.setForeground(new java.awt.Color(255, 255, 255));
        btnCapture.setText("Capture");
        btnCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaptureActionPerformed(evt);
            }
        });
        jPanel1.add(btnCapture);
        btnCapture.setBounds(150, 360, 100, 30);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(150, 80, 510, 10);

        txtVisitorName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVisitorNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVisitorNameFocusLost(evt);
            }
        });
        jPanel1.add(txtVisitorName);
        txtVisitorName.setBounds(150, 114, 510, 30);

        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });
        jPanel1.add(txtPhone);
        txtPhone.setBounds(150, 260, 510, 30);

        txtTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimeFocusLost(evt);
            }
        });
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        jPanel1.add(txtTime);
        txtTime.setBounds(150, 210, 510, 30);

        txtApartmentCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApartmentCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApartmentCodeFocusLost(evt);
            }
        });
        jPanel1.add(txtApartmentCode);
        txtApartmentCode.setBounds(150, 310, 510, 30);

        CapturingBack.setBackground(new java.awt.Color(0, 0, 0));
        CapturingBack.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        CapturingBack.setForeground(new java.awt.Color(255, 255, 255));
        CapturingBack.setText("Back");
        CapturingBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapturingBackActionPerformed(evt);
            }
        });
        jPanel1.add(CapturingBack);
        CapturingBack.setBounds(380, 360, 100, 30);

        btnRecords.setBackground(new java.awt.Color(0, 0, 0));
        btnRecords.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnRecords.setText("Records");
        jPanel1.add(btnRecords);
        btnRecords.setBounds(260, 360, 100, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Guest Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 100, 70, 16);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 230, 100, 50);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 130, 80, 50);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apartment Code");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 280, 90, 50);

        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateFocusLost(evt);
            }
        });
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtDate);
        txtDate.setBounds(150, 160, 510, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 190, 50, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartment_management/Background/pexels-artem-lysenko-3825673 (Background).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaptureActionPerformed
        
            
        if (txtVisitorName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Guest Name Field cannot be left empty");
            txtVisitorName.requestFocusInWindow();
        }
        else if (txtDate.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Date Field cannot be left empty");
            txtDate.requestFocusInWindow();
        }
        else if (txtTime.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Time Field cannot be left empty");
            txtTime.requestFocusInWindow();
        }
        else if (txtPhone.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Phone Number Field cannot be left empty");
            txtPhone.requestFocusInWindow();
        }
        else if (txtApartmentCode.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Apartment Code Field cannot be left empty");
            txtApartmentCode.requestFocusInWindow();
        }
        else {
            Dashboard_Page.AddRowToTable(new Object[]{
            txtDate.getText(),
            txtTime.getText(),
            txtVisitorName.getText(),
            txtPhone.getText(),
            txtApartmentCode.getText(),
        
        });
        ImageIcon Icon = new javax.swing.ImageIcon(getClass().getResource("icons8-checked-60.png"));
            JOptionPane.showMessageDialog(this, "Captured Successful !! ", "SUCCESSFULL", JOptionPane.PLAIN_MESSAGE, Icon);
        }
        txtDate.setText("");
        txtTime.setText("");
        txtVisitorName.setText("");
        txtPhone.setText("");
        txtApartmentCode.setText("");
        txtVisitorName.requestFocusInWindow();
    
    }//GEN-LAST:event_btnCaptureActionPerformed

    private void txtVisitorNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVisitorNameFocusGained
        
    }//GEN-LAST:event_txtVisitorNameFocusGained

    private void txtVisitorNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVisitorNameFocusLost
       
    }//GEN-LAST:event_txtVisitorNameFocusLost

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
        
    }//GEN-LAST:event_txtPhoneFocusLost

    private void txtTimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimeFocusGained
        
    }//GEN-LAST:event_txtTimeFocusGained

    private void txtTimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimeFocusLost
        
    }//GEN-LAST:event_txtTimeFocusLost

    private void txtApartmentCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApartmentCodeFocusGained
        
    }//GEN-LAST:event_txtApartmentCodeFocusGained

    private void txtApartmentCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApartmentCodeFocusLost
        
    }//GEN-LAST:event_txtApartmentCodeFocusLost

    private void CapturingBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapturingBackActionPerformed
        this.toBack();
        Dashboard.setVisible(true);
        Dashboard.toFront();
        this.hide();
    }//GEN-LAST:event_CapturingBackActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateFocusGained

    private void txtDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateFocusLost

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visitors_Capturing_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visitors_Capturing_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visitors_Capturing_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visitors_Capturing_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visitors_Capturing_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CapturingBack;
    private javax.swing.JButton btnCapture;
    private javax.swing.JButton btnRecords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtApartmentCode;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtVisitorName;
    // End of variables declaration//GEN-END:variables

  private void seticonImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8-building-50.png"))); 
    }  
}
